{% set name = "pyvista" %}
{% set version = "0.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c45a5e4c7ed140e4450f34fb6bc34a466f79e1e55faf409f3f47282b0212d40d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - imageio >=2.5.0
    - appdirs
    - vtk
    - scooby >=0.5.1
    - typing_extensions

test:
  imports:
    - pyvista

about:
  home: https://github.com/pyvista/pyvista
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 3D plotting and mesh analysis through a streamlined interface for the Visualization Toolkit (VTK)

  description: |
    PyVista: 3D plotting and mesh analysis through a streamlined interface for the Visualization Toolkit (VTK). PyVista is a helper module for the Visualization Toolkit (VTK) that takes a different approach on interfacing with VTK through NumPy and direct array access. This package provides a Pythonic, well-documented interface exposing VTK's powerful visualization backend to facilitate rapid prototyping, analysis, and visual integration of spatially referenced datasets. This module can be used for scientific plotting for presentations and research papers as well as a supporting module for other mesh dependent Python modules.
  doc_url: https://docs.pyvista.org/
  dev_url: https://github.com/pyvista/pyvista

extra:
  recipe-maintainers:
    - banesullivan
    - akaszynski
