travis:
  secure:
    BINSTAR_TOKEN: Q/uY9408MDsZ4RzscyOC9z4s0NzcAViiORWna0uzc/5fhCmLyIxWvm+7ky97atkb2mEaiDU0k106mZHsUMThX43PITEq+NWj15p0gktUkOIEnZLNnBfLJzsFsSnXOO6o2X5g6u06Sr/jALZW4NdATmJhqcHbV2EnCmhGXvHxBo3Hdl7wKjsUaXTQLUhzeqvbCQvokcXB/KWCzex8BYkK6MoeFrv6Vx4QMgc2M43VZOkTj2Q0DZ6tOAFv7Q1AbOqlBAYt+oVujGLJoLlwmLLgZ/atLqG71aRqyNuHzwSvPxNjhYLawcuCbRu3wKZ6+YpijAtcExkQuKnjslDcH3Q9LTajSBWrUZE1evdz31G/ybS0Sn4XXrkNYczMt72CWhAKDYnycj75QrPeUanzSmJ1UuMfJtfS+znXydaJ8941U1K6dsXOq+PbeKXPtea+XBkEPDYsa0LopYkJ9W7tCs9RRgbGFM747hP7VxNQrj45CedmZxc1gMq58L1sRFuyXyUk5cxOqsvJ5qc/jtpOgFd0WVOvnKktkGesaI8Jeg8YzqLu9u9jTq9FOTKbs3sX1cg+u7JfkoZAn8PBnxoiJHb67fr8rTIrVoG69UxunK8pI6QQRD1Vj+ogwpHeINqJhEz5TL9CO0U3Vt2lFOX2uqr3HK72MXyxwsyNAozWyk7mA7E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
